apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-corp-auth-rust-app
  namespace: dummy-corp-erp-namespace
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: dummy-corp-auth-rust-app
  template:
    metadata:
      labels:
        app: dummy-corp-auth-rust-app
    spec:
      containers:
      - name: dummy-corp-auth-rust-app
        image: localhost:32000/dummy-corp-auth-rust-app:latest  # Usar la imagen de tu registro local
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: postgres-config  # Referencia al ConfigMap
        - configMapRef:
            name: redis-config  # Referencia al ConfigMap
        env:
        - name: AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: auth-secret  # Nombre del secret
              key: AUTH_TOKEN  # Clave del secret
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret  # Nombre del secret
              key: REDIS_PASSWORD  # Clave del secret
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 32Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dummy-corp-auth-rust-app
  namespace: dummy-corp-erp-namespace
spec:
  selector:
    app: dummy-corp-auth-rust-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
