---
kind: ConfigMap
apiVersion: v1
metadata:
  name: auth-config
  namespace: dummy-corp-erp-namespace
data:
  AUTH_SERVICE_URL: http://dummy-corp-auth-rust-app:8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-corp-erp-golang-app
  namespace: dummy-corp-erp-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-corp-erp-golang-app
  template:
    metadata:
      labels:
        app: dummy-corp-erp-golang-app
    spec:
      containers:
      - name: dummy-corp-erp-golang-app
        image: localhost:32000/dummy-corp-erp-golang-app:latest  # Usar la imagen de tu registro local
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: postgres-config  # Referencia al ConfigMap
        - configMapRef:
            name: auth-config  # Referencia al ConfigMap
        env:
        - name: AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: auth-secret  # Nombre del secret
              key: AUTH_TOKEN    # Clave del secret
        - name: AUTH_SUPER_SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              name: auth-secret  # Nombre del secret
              key: AUTH_SUPER_SECRET_TOKEN  # Clave del secret         
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 32Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080  